# https://docs.microsoft.com/azure/devops/pipelines/languages/python
pool:
  vmImage: 'ubuntu-20.04' # other options: 'macOS-10.13', 'vs2017-win2016'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
- script: |
    echo 'Start pipeline'
  
    # Print the Linux version.
    uname -a
  
    python --version
  
    #pip install -r requirements.txt  # Note: There is no requirements.txt
  
    # python -m unittest discover tests/
    python -m unittest GccCoverageParser_UnitTest.py


- script: |
    echo 'Start pipeline'
  
    # Print the Linux version.
    uname -a
  
    python --version
  
    #pip install -r requirements.txt

    echo 'Test the python with empty arguments - like a system test'
    python Run_GccCoverage_ForSourceFiles.py
